balancers:
  rack:
    5443/https: https://rack:3000
services:
  rack:
    build: .
    test: make check test
workflows:
  change:
    create:
      - create: staging/praxis-$branch
      - build: staging/praxis-$branch
      - test
      - promote
    close:
      - delete: staging/praxis-$branch
  merge:
    demo:
      - deploy: demo/praxis-demo
    master:
      - build: staging/praxis-staging
      - test
      - promote
      - copy: production/praxis-production
      - promote